# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - newskit-engineering
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking change
    - title: New Features 🎉
      labels:
        - feature
    - title: Bug Fixes 🐛
      labels:
        - fix
    - title: Documentation 📝
      labels:
        - doc
    - title: Other Changes 🧱
      labels:
        - "*"