---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-{{ (datasource "config").Name }}-network-policy
  namespace: {{ (datasource "config").Namespace }}
spec:
  podSelector:
    matchExpressions :
      - {key: app, operator: In, values: [{{ (datasource "config").DocSiteName }},{{ (datasource "config").StorybookName }} ]}
  ingress:
  - ports:
    - port: 8081
      protocol: TCP
    - port: 6006
      protocol: TCP
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress  