---
apiVersion: v1
kind: Service
metadata:
  name: {{ (datasource "config").DocSiteName }}-loadbalancer-service
  namespace: {{ (datasource "config").Namespace }}
spec:
  type: NodePort
  selector:
    app: {{ (datasource "config").DocSiteName }}
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8081
    
---

apiVersion: v1
kind: Service
metadata:
  name: {{ (datasource "config").StorybookName }}-loadbalancer-service
  namespace: {{ (datasource "config").Namespace }}
spec:
  type: NodePort
  selector:
    app: {{ (datasource "config").StorybookName }}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 6006